# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            DeepAnalysisResearch
tagline:          'Homepage for DAR Team'
description:      'A website for Research and Blog shared from DAR Team'
url:              https://deep-analysis-research.github.io/
baseurl:          https://deep-analysis-research.github.io/

author:
  name:           'DeepAnalysisResearch'
  url:            

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/deep-analysis-research/
